name: 'Release notification'
description: 'Send a notification when a new release is published'
author: 'Jeff Nelson'
branding:
    icon: 'message-circle'
    color: 'yellow'
inputs:
    channel:
        description: 'The channel to send to'
        required: true
    message:
        description: 'The message to send'
        required: true
    context:
        description: Slack message context
        required: false
    actions:
        description: A JSON array string of Slack Action objects
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'
